config/routes.rb
Rails.application.routes.draw do
  resources :players
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/player.rb
class Player < ApplicationRecord
	def self.get_champions 
		p_ar = self.arel_table
    champions = []
    max_age_precedent = 0
    self.order(p_ar[:age].asc).pluck(:age).uniq.each_with_index do |age, i|
      max_age_actuel = self.where(age: age).maximum(:elo)
      max_age_precedent = max_age_actuel if i == 0
      if max_age_precedent < max_age_actuel || i == 0
        champions << self.where(age: age, elo: max_age_actuel).all
        max_age_precedent = max_age_actuel
      end
    end
    champions.flatten
	end

  def self.get_max_elo_by_age
    p_ar = self.arel_table
    all_high_score_by_age = []
    self.order(p_ar[:age].asc).pluck(:age).uniq.map do |age|
      max = self.where(age: age).maximum(:elo)
      all_high_score_by_age << self.where(age: age, elo: max).all.pluck(:id)
    end
    self.where(id: all_high_score_by_age.flatten).order(:age)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pagy::Backend
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]

  # GET /players or /players.json
  def index
    @pagy, @max_elo_by_age = pagy(Player.get_max_elo_by_age)
    @champions = Player.get_champions
  end

  # GET /players/1 or /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to player_url(@player), notice: "Player was successfully created." }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to player_url(@player), notice: "Player was successfully updated." }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url, notice: "Player was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:name, :elo, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	include Pagy::Frontend
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Faks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player) do |form| %>
  <% if player.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>
      <ul>
        <% player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="space-y-12">
   
    <div class="border-b border-gray-900/10 pb-12">
      <h2 class="text-base font-semibold leading-7 text-gray-900"><%= params[:action] == "edit" ? "Edit" : "New" %> Player</h2>

      <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
        <div class="col-span-full">
          <label for="street-address" class="block text-sm font-medium leading-6 text-gray-900">Name</label>
          <div class="mt-2">
            <%= form.text_field :name, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
          </div>
        </div>

        <div class="sm:col-span-2 sm:col-start-1">
          <label for="elo" class="block text-sm font-medium leading-6 text-gray-900">Elo</label>
          <div class="mt-2">
            <%= form.number_field :elo, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
          </div>
        </div>

        <div class="sm:col-span-2">
          <label for="age" class="block text-sm font-medium leading-6 text-gray-900">Age</label>
          <div class="mt-2">
            <%= form.number_field :age, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" %>
          </div>
        </div>

      </div>
    </div>

  </div>

  <div class="mt-6 flex items-center justify-end gap-x-6">
    <%= link_to "Cancel", players_path, class: "text-sm font-semibold leading-6 text-gray-900" %>
    <%= form.submit "Save", class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
  </div>
<% end %>

app/views/players/_player.html.erb
<div class="overflow-hidden bg-white shadow sm:rounded-lg">
  <div class="px-4 py-6 sm:px-6">
    <h3 class="text-base font-semibold leading-7 text-gray-900">Player Information</h3>
    <p class="mt-1 max-w-2xl text-sm leading-6 text-gray-500">Player details.</p>
  </div>
  <div class="border-t border-gray-100">
    <dl class="divide-y divide-gray-100">
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-900">Name</dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= player.name %></dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-900">Elo</dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= player.elo %></dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-900">Age</dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= player.age %></dd>
      </div>
   
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-900">Actions</dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0 flex">
          <%= link_to "Back to players", players_path, class: "text-sm font-semibold leading-6 text-gray-900 mr-3 pt-1" %>
          <%= link_to "Edit this player", edit_player_path(@player), class: "rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 mr-3" %>
          <%= button_to "Destroy this player", @player, method: :delete, class: "rounded-md bg-red-500 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-400" %>
        </dd>
      </div>
    </dl>
  </div>
</div>

app/views/players/edit.html.erb
<%= render "form", player: @player %>

app/views/players/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-base font-semibold leading-6 text-gray-900">Champions</h1>
      <p class="mt-2 text-sm text-gray-700">A list of the champions players including their name, elo and age.</p>
    </div>
  </div>
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 h-96 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-300">
          <thead>
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-3">#</th>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-3">Name</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Elo</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Age</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-3">
                <span class="sr-only">Show</span>
              </th>
            </tr>
          </thead>
          <tbody class="bg-white">
            <% @champions.each do |player| %>
              <tr class="even:bg-gray-50">
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-3"><%= player.id %></td>
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-3"><%= player.name %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= player.elo %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= player.age %></td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-3">
                  <%= link_to "Show", player, class: "text-indigo-600 hover:text-indigo-900" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>


<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-base font-semibold leading-6 text-gray-900">Max Elo by Age</h1>
      <p class="mt-2 text-sm text-gray-700">A list of all the max score by age including their name, elo and age.</p>
    </div>
    <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
      <%= link_to "New player", new_player_path, class: "block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"%>
    </div>
  </div>
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 h-96 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-300">
          <thead>
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-3">#</th>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-3">Name</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Elo</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Age</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-3">
                <span class="sr-only">Show</span>
              </th>
            </tr>
          </thead>
          <tbody class="bg-white">
            <% @max_elo_by_age.each do |player| %>
              <tr class="even:bg-gray-50">
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-3"><%= player.id %></td>
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-3"><%= player.name %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= player.elo %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= player.age %></td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-3">
                  <%= link_to "Show", player, class: "text-indigo-600 hover:text-indigo-900" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <nav class="bg-white px-4 py-3 flex items-center justify-between border-t border-gray-200 sm:px-6" aria-label="Pagination">
      <div class="hidden sm:block">
          <p class="text-sm text-gray-700">
            Showing
            <span class="font-medium"><%= @pagy.from %></span>
            to
            <span class="font-medium"><%= @pagy.to %></span>
            of
            <span class="font-medium"><%= @pagy.count %></span>
            results
          </p>
      </div>
      <div class="flex-1 flex justify-between sm:justify-end">
          <% if @pagy.prev %>    
          <%= link_to "Previous", players_path(page: @pagy.prev), class: "relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50" %>
          <% end %>
          <% if @pagy.next %>    
          <%= link_to "Next", players_path(page: @pagy.next), class: "ml-3 relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50" %>
          <% end %>
      </div>
    </nav>
  </div>
</div>

app/views/players/new.html.erb
<%= render "form", player: @player %>

app/views/players/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @player %>